-- Formatea strings y numeros de JSON para usar el validador
CREATE OR REPLACE FUNCTION str_num_json_validator() RETURNS VOID AS $$
BEGIN

	TRUNCATE alfabeto;
	INSERT INTO alfabeto (caracter) VALUES
	('0'), ('1'), ('2'), ('3'), ('4'), ('5'), ('6'), ('7'), ('8'), ('9'),
	('a'), ('b'), ('c'), ('d'), ('e'), ('f'), ('g'), ('h'), ('i'), ('j'), ('k'), ('l'), ('m'), ('n'), ('ñ'), ('o'), ('p'), ('q'), ('r'), ('s'), ('t'), ('u'), ('v'), ('w'), ('x'), ('y'), ('z'),
	('A'), ('B'), ('C'), ('D'), ('E'), ('F'), ('G'), ('H'), ('I'), ('J'), ('K'), ('L'), ('M'), ('N'), ('Ñ'), ('O'), ('P'), ('Q'), ('R'), ('S'), ('T'), ('U'), ('V'), ('W'), ('X'), ('Y'), ('Z'),
	(' '), ('.'), (','), (':'), (';'), ('¿'), ('?'), ('¡'), ('!'), ('('), (')'), ('['), (']'), ('{'), ('}'), ('/'), ('+'), ('-'), ('_'), ('<'), ('>'), ('='), ('@'), ('#'), ('$'), ('%'), ('^'), ('&'), ('*'), ('¬'), ('~'), ('`'), ('|'), ('\'), ('°'), ('"'), ('''');

	TRUNCATE programa;
	INSERT INTO programa (estado_ori, caracter_ori, estado_nue, caracter_nue, desplazamiento) VALUES

	('q0', '"', 'q"', '"', 'R'),
	('q0', '[', 'q0', '[', 'R'),
	('q0', '{', 'q0', '{', 'R'),
	('q0', ']', 'q0', ']', 'R'),
	('q0', '}', 'q0', '}', 'R'),
	('q0', ':', 'q0', ':', 'R'),
	('q0', ',', 'q0', ',', 'R'),
	('q0', ' ', 'q0', ' ', 'R'),
	('q0', 'n', 'q0', 'n', 'R'),
	('q0', 'u', 'q0', 'u', 'R'),
	('q0', 'l', 'q0', 'l', 'R'),
	('q0', 't', 'q0', 't', 'R'),
	('q0', 'r', 'q0', 'r', 'R'),
	('q0', 'e', 'q0', 'e', 'R'),
	('q0', 'f', 'q0', 'f', 'R'),
	('q0', 'a', 'q0', 'a', 'R'),
	('q0', 's', 'q0', 's', 'R'),
	('q0', 'B', 'qf', 'B', 'R'),

	-- Numeros
	('q0', '-', 'qn-', '0', 'R'),
	('q0', '0', 'qn0', '0', 'R'),
	('q0', '1', 'qn', '0', 'R'),
	('q0', '2', 'qn', '0', 'R'),
	('q0', '3', 'qn', '0', 'R'),
	('q0', '4', 'qn', '0', 'R'),
	('q0', '5', 'qn', '0', 'R'),
	('q0', '6', 'qn', '0', 'R'),
	('q0', '7', 'qn', '0', 'R'),
	('q0', '8', 'qn', '0', 'R'),
	('q0', '9', 'qn', '0', 'R'),

	-- Numeros que arrancan con 0
	('qn0', '.', 'qnd', '0', 'R'),
	('qn0', 'e', 'qne', '0', 'R'),
	('qn0', 'E', 'qne', '0', 'R'),

	-- Numeros negativos
	('qn-', '0', 'qn0', '0', 'R'),
	('qn-', '1', 'qn', '0', 'R'),
	('qn-', '2', 'qn', '0', 'R'),
	('qn-', '3', 'qn', '0', 'R'),
	('qn-', '4', 'qn', '0', 'R'),
	('qn-', '5', 'qn', '0', 'R'),
	('qn-', '6', 'qn', '0', 'R'),
	('qn-', '7', 'qn', '0', 'R'),
	('qn-', '8', 'qn', '0', 'R'),
	('qn-', '9', 'qn', '0', 'R'),

	-- Principio de los numeros
	('qn', '.', 'qnd', '0', 'R'),
	('qn', 'e', 'qne', '0', 'R'),
	('qn', 'E', 'qne', '0', 'R'),
	('qn', '0', 'qn', '0', 'R'),
	('qn', '1', 'qn', '0', 'R'),
	('qn', '2', 'qn', '0', 'R'),
	('qn', '3', 'qn', '0', 'R'),
	('qn', '4', 'qn', '0', 'R'),
	('qn', '5', 'qn', '0', 'R'),
	('qn', '6', 'qn', '0', 'R'),
	('qn', '7', 'qn', '0', 'R'),
	('qn', '8', 'qn', '0', 'R'),
	('qn', '9', 'qn', '0', 'R'),
	('qn', ',', 'q0', ',', 'R'),
	('qn', ']', 'q0', ']', 'R'),
	('qn', '}', 'q0', '}', 'R'),
	('qn', ' ', 'q0', ' ', 'R'),
	('qn', 'B', 'q0', 'B', 'R'),

	-- Numeros decimales
	('qnd', 'e', 'qne', '0', 'R'),
	('qnd', 'E', 'qne', '0', 'R'),
	('qnd', '0', 'qnd', '0', 'R'),
	('qnd', '1', 'qnd', '0', 'R'),
	('qnd', '2', 'qnd', '0', 'R'),
	('qnd', '3', 'qnd', '0', 'R'),
	('qnd', '4', 'qnd', '0', 'R'),
	('qnd', '5', 'qnd', '0', 'R'),
	('qnd', '6', 'qnd', '0', 'R'),
	('qnd', '7', 'qnd', '0', 'R'),
	('qnd', '8', 'qnd', '0', 'R'),
	('qnd', '9', 'qnd', '0', 'R'),
	('qnd', ',', 'q0', ',', 'R'),
	('qnd', ']', 'q0', ']', 'R'),
	('qnd', '}', 'q0', '}', 'R'),
	('qnd', ' ', 'q0', ' ', 'R'),
	('qnd', 'B', 'q0', 'B', 'R'),

	-- Notacion Cientifica
	('qne', '-', 'qne-', '0', 'R'),
	('qne', '0', 'qnc', '0', 'R'),
	('qne', '1', 'qnc', '0', 'R'),
	('qne', '2', 'qnc', '0', 'R'),
	('qne', '3', 'qnc', '0', 'R'),
	('qne', '4', 'qnc', '0', 'R'),
	('qne', '5', 'qnc', '0', 'R'),
	('qne', '6', 'qnc', '0', 'R'),
	('qne', '7', 'qnc', '0', 'R'),
	('qne', '8', 'qnc', '0', 'R'),
	('qne', '9', 'qnc', '0', 'R'),

	('qne-', '0', 'qnc', '0', 'R'),
	('qne-', '1', 'qnc', '0', 'R'),
	('qne-', '2', 'qnc', '0', 'R'),
	('qne-', '3', 'qnc', '0', 'R'),
	('qne-', '4', 'qnc', '0', 'R'),
	('qne-', '5', 'qnc', '0', 'R'),
	('qne-', '6', 'qnc', '0', 'R'),
	('qne-', '7', 'qnc', '0', 'R'),
	('qne-', '8', 'qnc', '0', 'R'),
	('qne-', '9', 'qnc', '0', 'R'),

	('qnc', '0', 'qnc', '0', 'R'),
	('qnc', '1', 'qnc', '0', 'R'),
	('qnc', '2', 'qnc', '0', 'R'),
	('qnc', '3', 'qnc', '0', 'R'),
	('qnc', '4', 'qnc', '0', 'R'),
	('qnc', '5', 'qnc', '0', 'R'),
	('qnc', '6', 'qnc', '0', 'R'),
	('qnc', '7', 'qnc', '0', 'R'),
	('qnc', '8', 'qnc', '0', 'R'),
	('qnc', '9', 'qnc', '0', 'R'),
	('qnc', ',', 'q0', ',', 'R'),
	('qnc', ']', 'q0', ']', 'R'),
	('qnc', '}', 'q0', '}', 'R'),
	('qnc', ' ', 'q0', ' ', 'R'),
	('qnc', 'B', 'q0', 'B', 'R'),
	

	-- Cadenas
	('q"', '"', 'q0', '"', 'R'),	-- Termina la cadena
	('q"', '\', 'q\', 'w', 'R'),	-- Va a secuencias de escape

	-- Letras Minusculas en cadena
	('q"', 'a', 'q"', 'w', 'R'),
	('q"', 'b', 'q"', 'w', 'R'),
	('q"', 'c', 'q"', 'w', 'R'),
	('q"', 'd', 'q"', 'w', 'R'),
	('q"', 'e', 'q"', 'w', 'R'),
	('q"', 'f', 'q"', 'w', 'R'),
	('q"', 'g', 'q"', 'w', 'R'),
	('q"', 'h', 'q"', 'w', 'R'),
	('q"', 'i', 'q"', 'w', 'R'),
	('q"', 'j', 'q"', 'w', 'R'),
	('q"', 'k', 'q"', 'w', 'R'),
	('q"', 'l', 'q"', 'w', 'R'),
	('q"', 'm', 'q"', 'w', 'R'),
	('q"', 'n', 'q"', 'w', 'R'),
	('q"', 'ñ', 'q"', 'w', 'R'),
	('q"', 'o', 'q"', 'w', 'R'),
	('q"', 'p', 'q"', 'w', 'R'),
	('q"', 'q', 'q"', 'w', 'R'),
	('q"', 'r', 'q"', 'w', 'R'),
	('q"', 's', 'q"', 'w', 'R'),
	('q"', 't', 'q"', 'w', 'R'),
	('q"', 'u', 'q"', 'w', 'R'),
	('q"', 'v', 'q"', 'w', 'R'),
	('q"', 'w', 'q"', 'w', 'R'),
	('q"', 'x', 'q"', 'w', 'R'),
	('q"', 'y', 'q"', 'w', 'R'),
	('q"', 'z', 'q"', 'w', 'R'),
	
	-- Letras Mayusculas en cadena
	('q"', 'A', 'q"', 'w', 'R'),
	('q"', 'B', 'q"', 'w', 'R'),
	('q"', 'C', 'q"', 'w', 'R'),
	('q"', 'D', 'q"', 'w', 'R'),
	('q"', 'E', 'q"', 'w', 'R'),
	('q"', 'F', 'q"', 'w', 'R'),
	('q"', 'G', 'q"', 'w', 'R'),
	('q"', 'H', 'q"', 'w', 'R'),
	('q"', 'I', 'q"', 'w', 'R'),
	('q"', 'J', 'q"', 'w', 'R'),
	('q"', 'K', 'q"', 'w', 'R'),
	('q"', 'L', 'q"', 'w', 'R'),
	('q"', 'M', 'q"', 'w', 'R'),
	('q"', 'N', 'q"', 'w', 'R'),
	('q"', 'Ñ', 'q"', 'w', 'R'),
	('q"', 'O', 'q"', 'w', 'R'),
	('q"', 'P', 'q"', 'w', 'R'),
	('q"', 'Q', 'q"', 'w', 'R'),
	('q"', 'R', 'q"', 'w', 'R'),
	('q"', 'S', 'q"', 'w', 'R'),
	('q"', 'T', 'q"', 'w', 'R'),
	('q"', 'U', 'q"', 'w', 'R'),
	('q"', 'V', 'q"', 'w', 'R'),
	('q"', 'W', 'q"', 'w', 'R'),
	('q"', 'X', 'q"', 'w', 'R'),
	('q"', 'Y', 'q"', 'w', 'R'),
	('q"', 'Z', 'q"', 'w', 'R'),

	-- Numeros en cadena
	('q"', '0', 'q"', 'w', 'R'),
	('q"', '1', 'q"', 'w', 'R'),
	('q"', '2', 'q"', 'w', 'R'),
	('q"', '3', 'q"', 'w', 'R'),
	('q"', '4', 'q"', 'w', 'R'),
	('q"', '5', 'q"', 'w', 'R'),
	('q"', '6', 'q"', 'w', 'R'),
	('q"', '7', 'q"', 'w', 'R'),
	('q"', '8', 'q"', 'w', 'R'),
	('q"', '9', 'q"', 'w', 'R'),

	-- Simbolos validos dentro de una cadena
	('q"', ' ', 'q"', 'w', 'R'),
	('q"', '.', 'q"', 'w', 'R'),
	('q"', ',', 'q"', 'w', 'R'),
	('q"', ':', 'q"', 'w', 'R'),
	('q"', ';', 'q"', 'w', 'R'),
	('q"', '¿', 'q"', 'w', 'R'),
	('q"', '?', 'q"', 'w', 'R'),
	('q"', '¡', 'q"', 'w', 'R'),
	('q"', '!', 'q"', 'w', 'R'),
	('q"', '(', 'q"', 'w', 'R'),
	('q"', ')', 'q"', 'w', 'R'),
	('q"', '[', 'q"', 'w', 'R'),
	('q"', ']', 'q"', 'w', 'R'),
	('q"', '{', 'q"', 'w', 'R'),
	('q"', '}', 'q"', 'w', 'R'),

	('q"', '/', 'q"', 'w', 'R'),
	('q"', '+', 'q"', 'w', 'R'),
	('q"', '-', 'q"', 'w', 'R'),
	('q"', '_', 'q"', 'w', 'R'),
	('q"', '<', 'q"', 'w', 'R'),
	('q"', '>', 'q"', 'w', 'R'),
	('q"', '=', 'q"', 'w', 'R'),

	('q"', '@', 'q"', 'w', 'R'),
	('q"', '#', 'q"', 'w', 'R'),
	('q"', '$', 'q"', 'w', 'R'),
	('q"', '%', 'q"', 'w', 'R'),
	('q"', '^', 'q"', 'w', 'R'),
	('q"', '&', 'q"', 'w', 'R'),
	('q"', '*', 'q"', 'w', 'R'),

	('q"', '¬', 'q"', 'w', 'R'),
	('q"', '~', 'q"', 'w', 'R'),
	('q"', '`', 'q"', 'w', 'R'),
	('q"', '|', 'q"', 'w', 'R'),
	('q"', '°', 'q"', 'w', 'R'),
	('q"', '''', 'q"', 'w', 'R'),

	-- Secuencias de escape validas
	('q\', '"', 'q\', 'w', 'R'),	-- Quotation Mark
	('q\', '\', 'q\', 'w', 'R'),	-- Backslash
	('q\', '/', 'q\', 'w', 'R'),	-- Forward Slash
	('q\', 'b', 'q\', 'w', 'R'),	-- Backspace
	('q\', 'f', 'q\', 'w', 'R'),	-- Form Feed
	('q\', 'n', 'q\', 'w', 'R'),	-- Line Feed
	('q\', 'r', 'q\', 'w', 'R'),	-- Carriage Return
	('q\', 't', 'q\', 'w', 'R'),	-- Horizontal Tab
	('q\', 'u', 'qu', 'w', 'R'),	-- Unicode

	-- Primer Digito hexa del unicode
	('q\uX', '0', 'q\uXX', 'w', 'R'),
	('q\uX', '1', 'q\uXX', 'w', 'R'),
	('q\uX', '2', 'q\uXX', 'w', 'R'),
	('q\uX', '3', 'q\uXX', 'w', 'R'),
	('q\uX', '4', 'q\uXX', 'w', 'R'),
	('q\uX', '5', 'q\uXX', 'w', 'R'),
	('q\uX', '6', 'q\uXX', 'w', 'R'),
	('q\uX', '7', 'q\uXX', 'w', 'R'),
	('q\uX', '8', 'q\uXX', 'w', 'R'),
	('q\uX', '9', 'q\uXX', 'w', 'R'),
	('q\uX', 'A', 'q\uXX', 'w', 'R'),
	('q\uX', 'B', 'q\uXX', 'w', 'R'),
	('q\uX', 'C', 'q\uXX', 'w', 'R'),
	('q\uX', 'D', 'q\uXX', 'w', 'R'),
	('q\uX', 'E', 'q\uXX', 'w', 'R'),
	('q\uX', 'F', 'q\uXX', 'w', 'R'),
	('q\uX', 'a', 'q\uXX', 'w', 'R'),
	('q\uX', 'b', 'q\uXX', 'w', 'R'),
	('q\uX', 'c', 'q\uXX', 'w', 'R'),
	('q\uX', 'd', 'q\uXX', 'w', 'R'),
	('q\uX', 'e', 'q\uXX', 'w', 'R'),
	('q\uX', 'f', 'q\uXX', 'w', 'R'),
	
	-- Segundo Digito hexa del unicode
	('q\uXX', '0', 'q\uXXX', 'w', 'R'),
	('q\uXX', '1', 'q\uXXX', 'w', 'R'),
	('q\uXX', '2', 'q\uXXX', 'w', 'R'),
	('q\uXX', '3', 'q\uXXX', 'w', 'R'),
	('q\uXX', '4', 'q\uXXX', 'w', 'R'),
	('q\uXX', '5', 'q\uXXX', 'w', 'R'),
	('q\uXX', '6', 'q\uXXX', 'w', 'R'),
	('q\uXX', '7', 'q\uXXX', 'w', 'R'),
	('q\uXX', '8', 'q\uXXX', 'w', 'R'),
	('q\uXX', '9', 'q\uXXX', 'w', 'R'),
	('q\uXX', 'A', 'q\uXXX', 'w', 'R'),
	('q\uXX', 'B', 'q\uXXX', 'w', 'R'),
	('q\uXX', 'C', 'q\uXXX', 'w', 'R'),
	('q\uXX', 'D', 'q\uXXX', 'w', 'R'),
	('q\uXX', 'E', 'q\uXXX', 'w', 'R'),
	('q\uXX', 'F', 'q\uXXX', 'w', 'R'),
	('q\uXX', 'a', 'q\uXXX', 'w', 'R'),
	('q\uXX', 'b', 'q\uXXX', 'w', 'R'),
	('q\uXX', 'c', 'q\uXXX', 'w', 'R'),
	('q\uXX', 'd', 'q\uXXX', 'w', 'R'),
	('q\uXX', 'e', 'q\uXXX', 'w', 'R'),
	('q\uXX', 'f', 'q\uXXX', 'w', 'R'),
	
	-- Tercer Digito hexa del unicode
	('q\uXXX', '0', 'q\uXXXX', 'w', 'R'),
	('q\uXXX', '1', 'q\uXXXX', 'w', 'R'),
	('q\uXXX', '2', 'q\uXXXX', 'w', 'R'),
	('q\uXXX', '3', 'q\uXXXX', 'w', 'R'),
	('q\uXXX', '4', 'q\uXXXX', 'w', 'R'),
	('q\uXXX', '5', 'q\uXXXX', 'w', 'R'),
	('q\uXXX', '6', 'q\uXXXX', 'w', 'R'),
	('q\uXXX', '7', 'q\uXXXX', 'w', 'R'),
	('q\uXXX', '8', 'q\uXXXX', 'w', 'R'),
	('q\uXXX', '9', 'q\uXXXX', 'w', 'R'),
	('q\uXXX', 'A', 'q\uXXXX', 'w', 'R'),
	('q\uXXX', 'B', 'q\uXXXX', 'w', 'R'),
	('q\uXXX', 'C', 'q\uXXXX', 'w', 'R'),
	('q\uXXX', 'D', 'q\uXXXX', 'w', 'R'),
	('q\uXXX', 'E', 'q\uXXXX', 'w', 'R'),
	('q\uXXX', 'F', 'q\uXXXX', 'w', 'R'),
	('q\uXXX', 'a', 'q\uXXXX', 'w', 'R'),
	('q\uXXX', 'b', 'q\uXXXX', 'w', 'R'),
	('q\uXXX', 'c', 'q\uXXXX', 'w', 'R'),
	('q\uXXX', 'd', 'q\uXXXX', 'w', 'R'),
	('q\uXXX', 'e', 'q\uXXXX', 'w', 'R'),
	('q\uXXX', 'f', 'q\uXXXX', 'w', 'R'),
	
	-- Cuarto Digito hexa del unicode
	('q\uXXXX', '0', 'q"', 'w', 'R'),
	('q\uXXXX', '1', 'q"', 'w', 'R'),
	('q\uXXXX', '2', 'q"', 'w', 'R'),
	('q\uXXXX', '3', 'q"', 'w', 'R'),
	('q\uXXXX', '4', 'q"', 'w', 'R'),
	('q\uXXXX', '5', 'q"', 'w', 'R'),
	('q\uXXXX', '6', 'q"', 'w', 'R'),
	('q\uXXXX', '7', 'q"', 'w', 'R'),
	('q\uXXXX', '8', 'q"', 'w', 'R'),
	('q\uXXXX', '9', 'q"', 'w', 'R'),
	('q\uXXXX', 'A', 'q"', 'w', 'R'),
	('q\uXXXX', 'B', 'q"', 'w', 'R'),
	('q\uXXXX', 'C', 'q"', 'w', 'R'),
	('q\uXXXX', 'D', 'q"', 'w', 'R'),
	('q\uXXXX', 'E', 'q"', 'w', 'R'),
	('q\uXXXX', 'F', 'q"', 'w', 'R'),
	('q\uXXXX', 'a', 'q"', 'w', 'R'),
	('q\uXXXX', 'b', 'q"', 'w', 'R'),
	('q\uXXXX', 'c', 'q"', 'w', 'R'),
	('q\uXXXX', 'd', 'q"', 'w', 'R'),
	('q\uXXXX', 'e', 'q"', 'w', 'R'),
	('q\uXXXX', 'f', 'q"', 'w', 'R');


END;
$$ LANGUAGE plpgsql;

select str_num_json_validator();
